spring.application.name=service-registry

server.port = 8761

eureka.client.fetch-registry = false
eureka.client.registry-with-eureka=false
eureka.client.dashboard = true

eureka.instance.hostname = localhost
eureka.instance.instance-id = ${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address = true