spring.application.name = api-gateway

server.port = 8010

eureka.client.service-url.default-zone = http://localhost:8761

eureka.client.gateway.discovery.locator.enabled = true
eureka.client.gateway.discovery.locator.lower-case-service-id = true

eureka.instance.hostname = localhost
eureka.instance.instance-id = ${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# POLICY SERVICE
spring.cloud.gateway.routes[1].id=policy-service
spring.cloud.gateway.routes[1].uri=lb://policy-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/policy/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# CLAIM SERVICE
spring.cloud.gateway.routes[2].id=claim-service
spring.cloud.gateway.routes[2].uri=lb://claim-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/claim/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# Document SERVICE
spring.cloud.gateway.routes[3].id=document-service
spring.cloud.gateway.routes[3].uri=lb://document-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/document/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

logging.level.org.springframework.security=DEBUG

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true