spring.application.name=policy-service
server.port=8050


eureka.client.service-url.default-zone = http://localhost:8761

eureka.client.gateway.discovery.locator.enabled = true
eureka.client.gateway.discovery.locator.lower-case-service-id = true

eureka.instance.hostname = localhost
eureka.instance.instance-id = ${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

#spring.datasource.url=jdbc:mysql://localhost:3306/insurepro
#spring.datasource.username=root
#spring.datasource.password=Valluri@2024
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer



